# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: samitizerxu/math-easy-medium
dataset_configs:
  - train
system_prompt: "Please reflect and verify while reasoning and put the answer in \\boxed{}."

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: false
eval_strategy: "no"
# eval_steps: 100
gradient_accumulation_steps: 3
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: samitizerxu/Qwen2.5-R1-Distill-GRPO-em
hub_strategy: every_save
learning_rate: 3.0e-06
log_completions: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 400
max_completion_length: 16384
max_steps: -1
num_generations: 7
num_train_epochs: 1
output_dir: data/Qwen2.5-R1-Distill-GRPO-em
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
report_to:
  - wandb
reward_funcs:
  - accuracy
  - format
reward_weights:
  - 1.0
  - 1.0
save_strategy: "epoch"
seed: 2
warmup_ratio: 0.1
